// Generated by nuxi
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />
<<<<<<< HEAD
/// <reference path="types/builder-env.d.ts" />
=======
>>>>>>> ac296143c5419b93c87a3840ce72df6a5c3151ca
/// <reference types="nuxt" />
/// <reference path="types/app-defaults.d.ts" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/build.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
